version: "3"
services:
  db:
    image: mysql:5.7.31
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/dn-fad-app
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: ${SOURCE_HOME_DIR}
      dockerfile: ./Dockerfile
    #command: bundle exec rails s -p 3000 -b "0.0.0.0"
    # env_file:
    #   - .env
    volumes:
      - ${SOURCE_HOME_DIR}:/dn-fad-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data:
